Fix load_rcs1 again

diff --git a/bashrc-common b/bashrc-common
--- a/bashrc-common
+++ b/bashrc-common
@@ -370,7 +370,7 @@ function load_rcs1 {
         [[ -z $path ]] && continue
         [[ -f $path ]] || continue
         echo "$path"
-    done < <( /bin/ls -1 ${rootDir}/.taskrc/ 2>/dev/null | egrep -v '\.vim$' | sort )
+    done < <( /bin/ls -1 ${rootDir}/.taskrc/ 2>/dev/null | egrep -v '\.vim$' | sort | sed -e "s%^%${rootDir}/.taskrc/%" )
 }
 
 function loadTaskrcs {
@@ -388,20 +388,10 @@ function loadTaskrcs {
 		if [[ -f $line ]]; then
 		    xlog_rc "$line"
             source $line
-            [[ $? == 0 ]] || { echo "Error sourcing [$line] in loadTaskrcs()" >> $logfile9; return; }
+            [[ $? == 0 ]] || { echo "Error sourcing [$line] in loadTaskrcs()" >> $logfile9;  }
         fi
     done < <( load_rcs1 "$HOME" )
 
-	# Do it for any local .taskrc's in current dir also:
-	# if [[ "$HOME" != "$PWD" ]]; then
-    #     while read line; do
-    #         if [[ -f $line ]]; then
-    #             xlog_rc "$line"
-    #             source $line
-    #             [[ $? == 0 ]] || { echo "Error sourcing [$line] in loadTaskrcs()" >> $logfile9; return; }
-    #         fi
-    #     done < <( load_rcs1 "$PWD" )
-    # fi
 }
 
 function reset {
