Don't export errExit

diff --git a/bashrc-common b/bashrc-common
--- a/bashrc-common
+++ b/bashrc-common
@@ -92,12 +92,16 @@ function isSunos {
 }
 
 
-function errExit {
+errExit() {
     echo "ERROR: $*" >&2
     exit 1
 }
 
-export -f errExit
+die() {
+    echo "ERROR: $*" >&2
+    exit 1
+}
+
 
 
 
