Sync by ~/bin/cron-git-daily-maint.sh

diff --git a/basic_shell b/basic_shell
--- a/basic_shell
+++ b/basic_shell
@@ -8,6 +8,11 @@ cd $HOME
 while true; do
     (
         bash
+        if [[  $? -ne 0 ]]; then
+            echo "bash returned  an error" >&2
+            read
+            exit 1
+        fi
         reset
         echo "You are in a basic_shell loop ($1).  Kill $$ to quit"
     )
diff --git a/code-edit b/code-edit
--- a/code-edit
+++ b/code-edit
@@ -5,6 +5,11 @@ function code-edit_f {
         while true; do
             cd $EqststTop
             ~/bin/vim-eqstst
+            if [[ $? -ne 0 ]]; then
+                echo "vim failed to load." >&2
+                read
+                exit 1
+            fi
             echo "MARSTOP=$MARSTOP"
             echo " You're in an endless code-edit loop. Exit will return to editor.  Kill $$ to really escape the loop."
             bash
diff --git a/journal-edit b/journal-edit
--- a/journal-edit
+++ b/journal-edit
@@ -5,6 +5,11 @@ function journal-edit {
         while true; do
             cd $HOME/journal
             $EDITOR ./worklog.jrnl
+            if [[ $? -ne 0 ]]; then
+                echo "$EDITOR returned an error" >&2
+                read
+                exit 1
+            fi
             echo " You're in an endless journal-edit loop. Exit will return to editor.  Kill $$ to really escape the loop."
             bash
         done
