Fixed Ctrl+C handling for buildsrv

diff --git a/buildsrv-send b/buildsrv-send
--- a/buildsrv-send
+++ b/buildsrv-send
@@ -24,16 +24,41 @@ function killDeadTails {
     fi
 }
 
+
 function outwatcher {
     # monitor the stream for our end of job marker
     local line
     while read line; do
         if [[ "$line" == *end-of-job* ]]; then
+            echo "End of job detected"
             killDeadTails
+            kill $PPID
             exit 1
         fi
         echo "$line"
     done
+}
+
+function handle_ctrl_c {
+    # when the user hits Ctrl+C on the client, we need to echo that signal 
+    # to the remote_bash_run processes as 'die!':
+    echo -n "Client-side Ctrl+C: "
+    local serverPids=$( ps -U $UID -f | grep remote_bash_run | grep -v grep | awk '{print $2}')
+    if [[ ! -z "$serverPids" ]]; then
+        echo "Killing server pid(s):  ${serverPids}"
+        #echo "quit" > ~/tmp/buildsrv-in &
+        # When we kill the build process, that will bubble through back to us
+        # as an end-of-job from buildsrv, so we don't need to commit suicide.
+        kill ${serverPids}
+        read -t 3 line <~/tmp/buildsrv-out  # Clean up the tail of the pipe
+        echo "$line"
+        read -t 3 line <~/tmp/buildsrv-out  # Clean up the tail of the pipe
+        echo "$line"
+    else
+        # Suicide.  Something's wrong on the other end.
+        echo "Can't find server pids.  Client suicide:"
+        kill -9 $$ 
+    fi
 }
 
 
@@ -41,6 +66,7 @@ killDeadTails
 
 echo "$*" > ~/tmp/buildsrv-in
 
+trap 'handle_ctrl_c' SIGINT
 tail -f ~/tmp/buildsrv-out | outwatcher
 
 
