Smarter codesrv handling of dead sessions

diff --git a/codesrv-connect b/codesrv-connect
--- a/codesrv-connect
+++ b/codesrv-connect
@@ -18,13 +18,13 @@
 #        instance started in step #1
 #
 #  Cleanup:
-#    - Delete abandoned .codesrv-connect files when their vscode sessions die.
+#    - Delete abandoned .codesrv-connect files by running codesrv-status
 #    - Add .codesrv-connect to .gitignore
 #
 #  Notes:
 #     The VSCODE_IPC_HOOK_CLI environment variable points to a socket which is rather volatile, while the long path for the 'code' alias is more stable: vscode doesn't change the latter even across a "code -r ." reload.  But the former is easily detached and so you need a fresh value if that happens.  This is what codesrv-connect does: it captures the value of these two and writes them to .codesrv-connect in the current dir.
 #
-#   Verinfo: v1.0.1 - les.matheson@gmail.com - 2020-03-31
+#   Verinfo: v1.1.0 - les.matheson@gmail.com - 2020-04-27
 #
 
 function errExit {
@@ -32,9 +32,9 @@ function errExit {
     exit 1
 }
 
-[[ -S $VSCODE_IPC_HOOK_CLI ]] || errExit "VSCODE_IPC_HOOK_CLI not defined or not a pipe [$VSCODE_IPC_HOOK_CLI]"
+[[ -S $VSCODE_IPC_HOOK_CLI ]] || errExit "VSCODE_IPC_HOOK_CLI not defined or not a pipe [$VSCODE_IPC_HOOK_CLI].  Start an integrated terminal in vscode and then run codesrv-connect within that shell."
 if [[ $(which code) != *vscode-server* ]]; then
-    errExit "The 'code' command doesn't refer to something under .vscode-server: $(type -a code)"
+    errExit "The 'code' command doesn't refer to something under .vscode-server: $(type -a code).  Start an integrated terminal in vscode and then run codesrv-connect within that shell."
 fi
 if ! which pathadd &>/dev/null; then
     errExit "Cant find pathadd on the PATH"
@@ -42,21 +42,30 @@ fi
 
 codepath=$(echo $PATH | awk '/vscode-server/ {print $1}' RS=":")
 
-cat >.codesrv-connect <<EOF 
-# Temp file created by $(which codesrv-connect): source this into your working shell like '. .codesrv-connect'
-# ( git hint: add ".codesrv-connect" to .gitignore )
-#
-cd "$PWD"
-if ! test -S "$VSCODE_IPC_HOOK_CLI"; then
-    echo "ERROR: $VSCODE_IPC_HOOK_CLI not a socket. Dead session."
-else
-    export VSCODE_IPC_HOOK_CLI="$VSCODE_IPC_HOOK_CLI"
-    alias code=$(which code)
-    PATH=\$(pathadd "${codepath}")
-    echo "Done: the 'code' command will talk to socket \"$VSCODE_IPC_HOOK_CLI\" now."
-    echo "You can delete .codesrv-connect when the vscode server context dies, or reuse it in other shells until then."
-fi
-EOF
+cat >.codesrv-connect <<- EOF
+	# Temp file created by $(which codesrv-connect): source this into your working
+	#  shell like '. .codesrv-connect'
+	# ( git hint: add ".codesrv-connect" to .gitignore )
+	#
+
+	cd "$PWD"
+	if ! test -S "$VSCODE_IPC_HOOK_CLI"; then
+	    echo "ERROR: $VSCODE_IPC_HOOK_CLI not a socket. Dead session."
+	else
+	    export VSCODE_IPC_HOOK_CLI="$VSCODE_IPC_HOOK_CLI"
+	    if ! PATH=${codepath}:$PATH codesrv-status; then
+	        echo "ERROR: dead vscode connection.  Deleting dead context info: $VSCODE_IPC_HOOK_CLI"
+            rm $VSCODE_IPC_HOOK_CLI
+            rm .codesrv-connect
+	    else
+	        alias code=$(which code)
+	        PATH=\$(pathadd "${codepath}")
+	        echo "OK: the 'code' command will talk to socket \"$VSCODE_IPC_HOOK_CLI\" now."
+	        echo "You can use this command to connect other shells to this code server:"
+	        echo "   cd $PWD; codesrv"
+        fi
+	fi
+	EOF
 
 echo "# OK: run 'codesrv' to connect to vscode server in a destination shell, or this command:"
 echo ". $PWD/.codesrv-connect"
