Re-fixed codesrv-connect integrity check

diff --git a/codesrv-connect b/codesrv-connect
--- a/codesrv-connect
+++ b/codesrv-connect
@@ -53,10 +53,13 @@ cat >.codesrv-connect <<- EOF
 	    echo "ERROR: $VSCODE_IPC_HOOK_CLI not a socket. Dead session."
 	else
 	    export VSCODE_IPC_HOOK_CLI="$VSCODE_IPC_HOOK_CLI"
-	    if ! [[ \$PATH == *${codepath}* ]]; then
-	        echo "ERROR: dead vscode connection.  Deleting dead context info: $VSCODE_IPC_HOOK_CLI"
-            rm $VSCODE_IPC_HOOK_CLI
-            rm .codesrv-connect
+	    if ! PATH="${codepath}:\$PATH" codesrv-status; then
+	        echo "ERROR: dead vscode connection."
+            read -n 1 -p "Delete dead context info $VSCODE_IPC_HOOK_CLI ? (y/n): "
+            if [[ \$REPLY =~ [yY] ]]; then
+                rm $VSCODE_IPC_HOOK_CLI
+                rm .codesrv-connect
+            fi
 	    else
 	        alias code=$(which code)
 	        PATH=\$(pathadd "${codepath}")
