Fix python detection for path_undupe

diff --git a/path_undupe b/path_undupe
--- a/path_undupe
+++ b/path_undupe
@@ -1,6 +1,10 @@
 # vim: filetype=sh
 # source this to de-duplicate dirs in PATH
 
+if ! /usr/bin/env python &>/dev/null; then
+    echo "ERROR: /usr/bin/env python: no python on the PATH"
+    exit 1
+fi
 if test -x $HOME/bin/path_undupe.py; then
     PATH=$($HOME/bin/path_undupe.py  "$PATH" )
 fi
