Lint pylintish

diff --git a/pylintish b/pylintish
--- a/pylintish
+++ b/pylintish
@@ -3,12 +3,12 @@
 # pylintish -- invoke pylint using the .pylintrc file found by searching dir ancestry
 
 die() {
-    echo "ERROR: $@" >&2
+    echo "ERROR: $*" >&2
     exit 1
 }
 
 which_py() {
-    which python3.9 python3.8 python3.7 | head -n 1
+    command -v python3.9 python3.8 python3.7 | head -n 1
 }
 
 find_rcfile() {
@@ -18,15 +18,16 @@ find_rcfile() {
             echo "${tgt_dir}/.pylintrc"
             return
         fi
-        tgt_dir="$(dirname $tgt_dir)"
-        [[ $tgt_dir == / ]] && return $(die "Failed to locate .pylintrc")
+        tgt_dir=$(dirname "$tgt_dir")
+        [[ $tgt_dir == / ]] && return "$(die Failed to locate .pylintrc)"
     done
 }
 
 main() {
-    local rcfile=$(find_rcfile)
+    local rcfile
+    rcfile=$(find_rcfile)
     [[ -n $rcfile ]] && local rcfile_arg="--rcfile=${rcfile}"
-    $PYTHON -m pylint $rcfile_arg "$@"
+    $PYTHON -m pylint "$rcfile_arg" "$@"
 }
 
 if [[ -z $sourceMe ]]; then
