set_bashdebug_mode improves

diff --git a/set_bashdebug_mode b/set_bashdebug_mode
--- a/set_bashdebug_mode
+++ b/set_bashdebug_mode
@@ -7,6 +7,12 @@ function set_bashdebug_mode {
     #   --tty [device]: send output to specified pty (e.g. -tty /dev/pts/112)
     #       (--tty implies --on as well, you don't have to add the latter)
     #   --gen1:  Generate the PS4 setting for use in other scripts
+    #
+    # Tips:
+    #    - Unset PROMPT_COMMAND to reduce noise in interactive use cases
+    #    - On the right-side in --tty mode, do 'clear; tty; cat' so manual
+    #      commentary can interweave with shell diagnostics
+    #
     function print_bad_bxdb {
         echo -e "\E[1;31mBad or no arg[$1]: use --on | --off | --tty /dev/pts/??? | --gen1\E[0m" >&2
         false
@@ -44,3 +50,30 @@ function set_bashdebug_mode {
         shift
     done
 }
+
+function set_bashdebug_tty() {
+    # Run this on the SUT side, after
+    # you start bashdebug_tty on the monitor side
+    local xtty=$1
+    [[ -e $xtty ]] || { 
+        echo "ERROR: expecting tty name as \$1" >&2;
+        echo " Hint: run bashdebug_tty on the monitor terminal first, then run set_bashdebug_tty [tty] on the SUT terminal."
+
+        false; return; 
+    }
+
+    unset PROMPT_COMMAND
+    set_bashdebug_mode --tty $xtty
+    echo "PROMPT_COMMAND has been disabled, tty=$xtty" >${BASH_XTRACEFD}
+}
+
+function bashdebug_tty() {
+    # Run this on the monitor side 
+    clear; 
+    echo "Run set_bashdebug_tty $(tty) on the SUT side now."
+    date; cat >/dev/null
+    echo " ::: end: $(date) ::: "
+    echo "-----------------------------------------"
+    echo
+}
+
